#!/bin/sh

# Find out script's dir, resolving any links to the script itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR/..
gsc -e '(compile-file "sdl" cc-options: "-w -I/usr/include/SDL" ld-options: "-lSDL")'
